flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  branding: "assets/images/logo.png"
  color_dark: "#121212"
  image_dark: "assets/images/logo.png"
  branding_dark: "assets/images/logo.png"

  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#FFFFFF"
    image_dark: "assets/images/logo.png"
    icon_background_color_dark: "#121212"

  android: true
  ios: true
  web: false
