// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YKkNcRIbFkVeiO-sBbA2zgJxEzm6rlM',
    appId: '1:620614484841:web:ac86320829e764bc41b3f8',
    messagingSenderId: '620614484841',
    projectId: 'wain-d2e28',
    authDomain: 'wain-d2e28.firebaseapp.com',
    storageBucket: 'wain-d2e28.firebasestorage.app',
    measurementId: 'G-EV5MVJZX2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7Bdo485hgvkMV4LljPnE0NZ03D-GrTM',
    appId: '1:620614484841:android:6098fc800d98b77a41b3f8',
    messagingSenderId: '620614484841',
    projectId: 'wain-d2e28',
    storageBucket: 'wain-d2e28.firebasestorage.app',
  );
}
